// export default class QlikConnection {

//   #host
//   #prefix
//   #port
//   #isSecure
//   #baseURL

//   constructor({ host, prefix, port, isSecure }) {
//     this.#host = host;
//     this.#prefix = prefix;
//     this.#port = port;
//     this.#isSecure = isSecure;
//     this.#baseURL = `${this.#isSecure ? 'https' : 'http'}://${this.#host}${this.#port ? ":" + this.#port : ""}/${this.#prefix}resources`;
//   }
  
//   connect = () => new Promise(resolve => {
//     this.#loadDependencies().then(() => {
//       window.requirejs.config({
//         baseUrl: this.#baseURL
//       });

//       window.requirejs(["js/qlik"], qlik => {
//         resolve(qlik);
//       });
//     });
//   })

//   #loadDependencies = async () => {
//     try {
//       const link = document.createElement('link');
//       link.rel = 'stylesheet';
//       link.href = `${this.#baseURL}/autogenerated/qlik-styles.css`;
//       document.head.appendChild(link);
//       link.loaded = new Promise((resolve) => {
//           link.onload = () => {
//               resolve();
//           };
//       });

//       const script = document.createElement('script');
//       script.src = `${this.#baseURL}/assets/external/requirejs/require.js`;
//       document.body.appendChild(script);
//       script.loaded = new Promise((resolve) => {
//           script.onload = () => {
//               resolve();
//           };
//       });

//       await Promise.all([link.loaded, script.loaded])
//     } catch (error) {
//       throw new Error(error);
//     }
//   }
// }

export default function QlikConnection({ host, prefix, port, isSecure }) {

  const baseURL = `${isSecure ? 'https' : 'http'}://${host}${port ? ":" + port : ""}${prefix}resources`;

  async function loadDependencies () {
    try {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = `${baseURL}/autogenerated/qlik-styles.css`;
      document.head.appendChild(link);
      link.loaded = new Promise((resolve) => {
          link.onload = () => {
              resolve();
          };
      });

      const script = document.createElement('script');
      script.src = `${baseURL}/assets/external/requirejs/require.js`;
      document.body.appendChild(script);
      script.loaded = new Promise((resolve) => {
          script.onload = () => {
              resolve();
          };
      });

      await Promise.all([link.loaded, script.loaded])
    } catch (error) {
      throw new Error(error);
    }
  }

  return new Promise(resolve => {
    loadDependencies().then(() => {
      window.require.config({
        baseUrl: baseURL
      });

      window.require(["js/qlik"], qlik => {
        resolve(qlik);
      });
    });
  });
}